# Starter pipeline

trigger:
- master

pool:
  vmImage: windows-latest

steps:
  
# Restore from a project scoped feed in the same organization
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    includeNuGetOrg: true
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    vsTestVersion: '16.0'
- task : VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'